networks:
  matrix_net:
    name: matrix_net

volumes:
  matrix_db:
    name: matrix_db
  matrix_turn:
    name: matrix_turn

services:
  demo:
    image: demo:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SKIP_TESTS: "false"
    # Service is inactive by default. Run normally via IDE. It will only start if the profile is explicitly enabled:
    #   docker compose --profile demo up (-d)
    profiles:
      - demo
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MATRIX_HOST: matrix.local
      MATRIX_USERNAME: admin
      MATRIX_PASSWORD: magentaerenfarve
      MATRIX_ROOM_ID: "!GhYHbLfNOTzPklsVQY:matrix.local"
    depends_on:
      - matrix-server
    networks:
      - matrix_net

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - matrix-server
    networks:
      - matrix_net
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  synapse-config:
    image: docker.io/matrixdotorg/synapse:latest
    container_name: synapse-config
    # Override the default entrypoint (/start.py) so we can run a conditional shell script.
    # Previously we passed 'sh -c ...' as arguments to /start.py which caused: "Unknown execution mode 'sh'".
    entrypoint: /bin/sh
    command:
      - -c
      - |
        set -eu
        echo "[synapse-config] Script start $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        if [ ! -f /data/homeserver.yaml ]; then
          echo "[synapse-config] Generating Synapse config..."
          /start.py generate
          echo "[synapse-config] Generation finished"
        else
          echo "[synapse-config] Synapse config already present, skipping"
        fi
        echo "[synapse-config] Script end"
    environment:
      - SYNAPSE_SERVER_NAME=matrix.local
      - SYNAPSE_REPORT_STATS=yes
    volumes:
      - ./synapse-data:/data
    networks:
      - matrix_net
    restart: "no"

  matrix-server:
    container_name: matrix-server
    image: docker.io/matrixdotorg/synapse:v1.92.2
    restart: unless-stopped
    depends_on:
      synapse-config:
        condition: service_completed_successfully
      matrix-db:
        condition: service_started
    hostname: matrix.local
    networks:
      matrix_net:
        aliases:
          - matrix.local
    ports:
      - 8008:8008/tcp
      - 8448:8448/tcp
    volumes:
      - ./synapse-data:/data
    environment:
      - POSTGRES_USER=synapse

  matrix-db:
    container_name: matrix-db
    image: docker.io/postgres:12-alpine
    restart: unless-stopped
    networks:
      - matrix_net
    volumes:
      - matrix_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=YOUR_POSTGRES_PWD_HERE
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C